spring.application.name=spring-dummy-app

# H2 database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
# username & password would be stored in a more secure location in real system (ie. Vault/secure DB)
spring.datasource.username=sa
spring.datasource.password=

#Auto-run schema & test data
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-h2.sql
spring.sql.init.data-locations=classpath:testData-h2.sql
spring.h2.console.enabled=true

spring.sql.init.continue-on-error=false
logging.level.org.springframework.jdbc.datasource.init=DEBUG

