spring.application.name=spring-dummy-app

# postgres database
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true

spring.flyway.enabled=false

spring.sql.init.continue-on-error=false
logging.level.org.springframework.jdbc.datasource.init=DEBUG