CREATE TABLE thread_reference
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thread_reference          VARCHAR(255),
    status                    VARCHAR(255),
    created_time_stamp        TIMESTAMP(6) WITHOUT TIME ZONE,
    last_updated_time_stamp   TIMESTAMP(6) WITHOUT TIME ZONE,
    thread_expiry_date        TIMESTAMP(6) WITHOUT TIME ZONE,
    associated_case_reference VARCHAR(255),
    CONSTRAINT pk_threadreference PRIMARY KEY (id)
);